---
name: superhtml
description: "SuperHTML: HTML Language Server and Templating Language Library"
homepage: https://github.com/kristoff-it/superhtml
licenses:
  - MIT
languages:
  - HTML
categories:
  - LSP

source:
  id: pkg:github/kristoff-it/superhtml@v0.5.3
  asset:
    - target: darwin_arm64
      file: aarch64-macos.tar.gz
      bin: superhtml
    - target: darwin_x64
      file: x86_64-macos.tar.gz
      bin: superhtml
    - target: linux_arm64
      file: aarch64-linux.tar.gz
      bin: superhtml
    - target: linux_x64
      file: x86_64-linux-musl.tar.gz
      bin: superhtml
    - target: linux_x86
      file: x86_64-linux-musl.tar.gz
      bin: superhtml
    - target: win_x86
      file: aarch64-windows.zip
      bin: superhtml.exe
    - target: win_x64
      file: x86_64-windows.zip
      bin: superhtml.exe

schemas:
  lsp: https://raw.githubusercontent.com/kristoff-it/superhtml/{{version}}/schema.json

bin:
  superhtml: "{{source.asset.bin}}"
